using System;
using System.Collections.Generic;

namespace ApplicantAPI_1._0.Models
{
    public partial class Bfmresponse
    {
        public int ResponseId { get; set; }
        public int? TestId { get; set; }
        public string RequestId { get; set; }
        public string MediaId { get; set; }
        public string BfmTrueId { get; set; }
        public int? Gender { get; set; }
        public double? StatusCode { get; set; }
        public double? StatusMessage { get; set; }
        public double? Scale1 { get; set; }
        public double? Scale2 { get; set; }
        public double? Scale3 { get; set; }
        public double? Scale4 { get; set; }
        public double? Scale5 { get; set; }
        public double? Scale6 { get; set; }
        public double? Scale7 { get; set; }
        public double? Scale8 { get; set; }
        public double? Scale9 { get; set; }
        public double? Scale10 { get; set; }
        public double? Scale11 { get; set; }
        public double? Scale12 { get; set; }
        public double? Scale13 { get; set; }
        public double? Scale14 { get; set; }
        public double? Scale15 { get; set; }
        public double? Scale16 { get; set; }
        public double? Scale17 { get; set; }
        public double? Scale18 { get; set; }
        public double? Scale19 { get; set; }
        public double? Scale20 { get; set; }
        public double? Scale21 { get; set; }
        public double? Scale22 { get; set; }
        public double? Scale23 { get; set; }
        public double? Scale24 { get; set; }
        public double? Scale25 { get; set; }
        public double? Scale26 { get; set; }
        public double? Scale27 { get; set; }
        public double? Scale28 { get; set; }
        public double? Scale29 { get; set; }
        public double? Scale30 { get; set; }
        public double? Scale31 { get; set; }
        public double? Scale32 { get; set; }
        public double? Scale33 { get; set; }
        public double? Scale34 { get; set; }
        public double? Scale35 { get; set; }
        public double? Scale36 { get; set; }
        public double? Scale37 { get; set; }
        public double? Scale38 { get; set; }
        public double? Scale39 { get; set; }
        public double? Scale40 { get; set; }
        public double? Scale41 { get; set; }
        public double? Scale42 { get; set; }
        public double? Scale43 { get; set; }
        public double? Scale44 { get; set; }
        public double? Scale45 { get; set; }
        public double? Scale46 { get; set; }
        public double? Scale47 { get; set; }
        public double? Scale48 { get; set; }
        public double? Scale49 { get; set; }
        public double? Scale50 { get; set; }
        public double? Scale51 { get; set; }
        public double? Scale52 { get; set; }
        public double? Scale53 { get; set; }
        public double? Scale54 { get; set; }
        public double? Scale55 { get; set; }
        public double? Scale56 { get; set; }
        public double? Scale57 { get; set; }
        public double? Scale58 { get; set; }
        public double? Scale59 { get; set; }
        public double? Scale60 { get; set; }
        public double? Scale61 { get; set; }
        public double? Scale62 { get; set; }
        public double? Scale63 { get; set; }
        public double? Scale64 { get; set; }
        public double? Scale65 { get; set; }
        public double? Scale66 { get; set; }
        public double? Scale67 { get; set; }
        public double? Scale68 { get; set; }
        public double? Scale69 { get; set; }
        public double? Scale70 { get; set; }
        public double? Scale71 { get; set; }
        public double? Scale72 { get; set; }
        public double? Scale73 { get; set; }
        public double? Scale74 { get; set; }
        public double? Scale75 { get; set; }
        public double? Scale76 { get; set; }
        public double? Scale77 { get; set; }
        public double? Scale78 { get; set; }
        public double? Scale79 { get; set; }
        public double? Scale80 { get; set; }
        public double? Scale81 { get; set; }
        public double? Scale82 { get; set; }
        public double? Scale83 { get; set; }
        public double? Scale84 { get; set; }
        public double? Scale85 { get; set; }
        public double? Scale86 { get; set; }
        public double? Scale87 { get; set; }
        public double? Scale88 { get; set; }
        public double? Scale89 { get; set; }
        public double? Scale90 { get; set; }
        public double? Scale91 { get; set; }
        public double? Scale92 { get; set; }
        public double? Scale93 { get; set; }
        public double? Scale94 { get; set; }
        public double? Scale95 { get; set; }
        public double? Scale96 { get; set; }
        public double? Scale97 { get; set; }
        public double? Scale98 { get; set; }
        public double? Scale99 { get; set; }
        public double? Scale100 { get; set; }
        public double? Scale101 { get; set; }
        public double? Scale102 { get; set; }
        public double? Scale103 { get; set; }
        public double? Scale104 { get; set; }
        public double? Scale105 { get; set; }
        public double? Scale106 { get; set; }
        public double? Scale107 { get; set; }
        public double? Scale108 { get; set; }
        public double? Scale109 { get; set; }
        public double? Scale110 { get; set; }
        public double? Scale111 { get; set; }
        public double? Scale112 { get; set; }
        public double? Scale113 { get; set; }
        public double? Scale114 { get; set; }
        public double? Scale115 { get; set; }
        public double? Scale116 { get; set; }
        public double? Scale117 { get; set; }
        public double? Scale118 { get; set; }
        public double? Scale119 { get; set; }
        public double? Scale120 { get; set; }
        public double? Scale121 { get; set; }
        public double? Scale122 { get; set; }
        public double? Scale123 { get; set; }
        public double? Scale124 { get; set; }
        public double? Scale125 { get; set; }
        public double? Scale126 { get; set; }
        public double? Scale127 { get; set; }
        public double? Scale128 { get; set; }
        public double? Scale129 { get; set; }
        public double? Scale130 { get; set; }
        public double? Scale131 { get; set; }
        public double? Scale132 { get; set; }
        public double? Scale133 { get; set; }
        public double? Scale134 { get; set; }
        public double? Scale135 { get; set; }
        public double? Scale136 { get; set; }
        public double? Scale137 { get; set; }
        public double? Scale138 { get; set; }
        public double? Scale139 { get; set; }
        public double? Scale140 { get; set; }
        public double? Scale141 { get; set; }
        public double? Scale142 { get; set; }
        public double? Scale143 { get; set; }
        public double? Scale144 { get; set; }
        public double? Scale145 { get; set; }
        public double? Scale146 { get; set; }
        public double? Scale147 { get; set; }
        public double? Scale148 { get; set; }
        public double? Scale149 { get; set; }
        public double? Scale150 { get; set; }
        public double? Scale151 { get; set; }
        public double? Scale152 { get; set; }
        public double? Scale153 { get; set; }
        public double? Scale154 { get; set; }
        public double? Scale155 { get; set; }
        public double? Scale156 { get; set; }
        public double? Scale157 { get; set; }
        public double? Scale158 { get; set; }
        public double? Scale159 { get; set; }
        public double? Scale160 { get; set; }
        public double? Scale161 { get; set; }
        public double? Scale162 { get; set; }
        public double? Scale163 { get; set; }
        public double? Scale164 { get; set; }
        public double? Scale165 { get; set; }
        public double? Scale166 { get; set; }
        public double? Scale167 { get; set; }
        public double? Scale168 { get; set; }
        public double? Scale169 { get; set; }
        public double? Scale170 { get; set; }
        public double? Scale171 { get; set; }
        public double? Scale172 { get; set; }
        public double? Scale173 { get; set; }
        public double? Scale174 { get; set; }
        public double? Scale175 { get; set; }
        public double? Scale176 { get; set; }
        public double? Scale177 { get; set; }
        public double? Scale178 { get; set; }
        public double? Scale179 { get; set; }
        public double? Scale180 { get; set; }
        public double? Scale181 { get; set; }
        public double? Scale182 { get; set; }
        public double? Scale183 { get; set; }
        public double? Scale184 { get; set; }
        public double? Scale185 { get; set; }
        public double? Scale186 { get; set; }
        public double? Scale187 { get; set; }
        public double? Scale188 { get; set; }
        public double? Scale189 { get; set; }
        public double? Scale190 { get; set; }
        public double? Scale191 { get; set; }
        public double? Scale192 { get; set; }
        public double? Scale193 { get; set; }
        public double? Scale194 { get; set; }
        public double? Scale195 { get; set; }
    }
}
